cart/urls.py
from django.urls import path

from . import views

app_name = "cart"


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart_item, name="remove_cart_item"),
    path('checkout/', views.checkout, name="checkout"),
    path('cancel_order/<id>/', views.cancel_order, name="cancel_order"),

    path('select-address/', views.select_address, name="select_address"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('store/', include('store.urls', namespace="store")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('wishlist/', include('wishlist.urls', namespace="wishlists")),
    path('admins/',include('customadmin.urls', namespace="customadmin")),
    path('', views.home, name='home'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customadmin/urls.py
from django.urls import path

from . import views

app_name = "customadmin"

urlpatterns = [
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_logout/', views.admin_logout, name='admin_logout'),
    path('tables/', views.admin_tab, name='admin_tab'),
    path('manage_user/', views.manage_user, name='manage_user'),
    path('block_user/<int:id>/', views.block_user, name='block_user'),

    path('manage_category/', views.manage_category, name='manage_category'),
    path('delete_category/<int:id>/',
         views.delete_category, name='delete_category'),
    path('edit_category/<int:id>/', views.edit_category, name='edit_category'),
    path('add_category/', views.add_category, name='add_category'),

    path('manage_product/', views.manage_product, name='manage_product'),
    path('add_product/', views.add_product, name='add_product'),
    path('delete_product/<int:id>/', views.delete_product, name='delete_product'),
    path('edit_product/<int:id>/', views.edit_product, name='edit_product'),

    path('manage_variation/', views.manage_variation, name='manage_variation'),
    path('add_variation/', views.add_variation, name='add_variation'),
    path('edit_variation/<int:id>/', views.edit_variation, name='edit_variation'),
    path('delete_variation/<int:id>/',
         views.delete_variation, name='delete_variation'),

    path('manage_order/', views.manage_order, name='manage_order'),
    path('edit_order/<int:id>/', views.edit_order, name='edit_order'),


    path('manage_discount/', views.manage_discount, name='manage_discount'),
    path('add_discount/', views.add_discount, name='add_discount'),
    path('edit_discount/<int:id>/', views.edit_discount, name='edit_discount'),
    path('delete_discount/<int:id>/',
         views.delete_discount, name='delete_discount'),

    path('sales_report/', views.sales_report, name='sales_report'),

]

orders/urls.py
from django.urls import path
from . import views

app_name="orders"


urlpatterns = [
    path('place-order', views.placeorder, name="placeorder"),
    path('my-order', views.my_orders, name="my_orders"),

    # razorpay
    path('proceed-to-pay', views.razorcheck, name="razorcheck"),
]

customadmin/models.py
from django.db import models

# Create your models here.

store/models.py
from tabnanny import verbose
from django.db import models
from category.models import Category
from django.urls import reverse

# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    descrbtion = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    offer = models.PositiveIntegerField(default=0)
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('store:product_detail', args=[self.slug,self.category.slug])

    def __str__(self):
        return self.product_name
    
    def get_price_by_colors(self, color):
        varit = Variation.objects.filter(variation_value=color).first()
        return self.price + varit.price


class VariationManager(models.Manager):
    use_for_related_fields = True
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choices = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,related_name="variations")
    variation_category = models.CharField(
        max_length=50, choices=variation_category_choices)
    price = models.IntegerField(default=0)
    variation_value = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=225)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'


class Color(models.Model):
    name=models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name
    
    def get_url(self):
        return reverse('store:products_by_color',args=[self.slug])


class Size(models.Model):
    name=models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse('store:products_by_size',args=[self.slug])

orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name', 'last_name', 'phone', 'email', 'address_line_1', 'address_line_2', 'country', 'state', 'city', 'pincode'
        ]

customadmin/views.py
import datetime

from django.contrib import auth, messages
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.decorators.cache import never_cache

from accounts.models import Account
from category.models import Category
from orders.models import Coupons, Order, OrderItems
from store.models import Product, Variation

from .forms import (CategoryEditForm, DiscountCouponForm, ItemCreateForm,
                    OrderForm, VariationForm)

# Create your views here.
a = Account.objects.filter(is_superadmin=True)


# admin tabs
def admin_tab(request):
    customer_count = Account.objects.filter(is_superadmin=False).count()
    item_count = Product.objects.all().count()
    product = Product.objects.all()
    order = OrderItems.objects.all()
    order_count = OrderItems.objects.all().count()
    context = {
        'customer_count': customer_count,
        'item_count': item_count,
        'product': product,
        'order': order,
        'order_count': order_count
    }
    return render(request, 'admins/tables.html', context)

# manage user


@user_passes_test(lambda u: u in a, login_url='customadmin:admin_login')
def manage_user(request):
    if 'q' in request.GET:
        q = request.GET['q']
        if q:
            users = Account.objects.order_by(
                '-id').filter(Q(first_name__icontains=q) | Q(last_name__icontains=q) | Q(email__icontains=q))
            for single_product in users:
                product1 = []
            for single_product in users:
                product1.append({
                    "id": single_product.id,
                    "first_name": single_product.first_name,
                    "last_name": single_product.last_name,
                    "username": single_product.username,
                    "email": single_product.email,
                    "phone_number": single_product.phone_number,
                    "date_joined": single_product.date_joined,
                    "last_login": single_product.last_login,
                    "is_active": single_product.is_active,

                })
            paginator = Paginator(product1, 10)
            page = request.GET.get('page')
            paged_products = paginator.get_page(page)
            context = {
                'users': paged_products,
            }
            # users_count = users.count()
            if not users.exists():
                messages.error(request, 'No Matching Datas')
                return render(request, 'admins/manage_user.html')
        else:
            return redirect('customadmin:manage_user', context)
    else:
        users = Account.objects.filter(is_superadmin=False).order_by('-id')
        for single_product in users:
            product1 = []
        for single_product in users:
            product1.append({
                "id": single_product.id,
                "first_name": single_product.first_name,
                "last_name": single_product.last_name,
                "username": single_product.username,
                "email": single_product.email,
                "phone_number": single_product.phone_number,
                "date_joined": single_product.date_joined,
                "last_login": single_product.last_login,
                "is_active": single_product.is_active,
            })

        paginator = Paginator(product1, 10)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
    context = {
        'users': paged_products,
    }
    return render(request, 'admins/manage_user.html', context)

# end manage_user

# blockuser


@user_passes_test(lambda u: u in a, login_url='customadmin:admin_login')
def block_user(request, id):
    account = Account.objects.get(id=id)

    if account.is_active:
        account.is_active = False
        account.save()
    else:
        account.is_active = True
        account.save()
    return redirect('customadmin:manage_user')

# blockuser end

# manage category


@user_passes_test(lambda u: u in a, login_url='customadmin:admin_login')
def manage_category(request):
    if 'q' in request.GET:
        q = request.GET['q']
        if q:
            category = Category.objects.order_by(
                '-id').filter(Q(title__icontains=q))
            # users_count = users.count()
            if not category.exists():
                messages.error(request, 'No Matching Datas Found')
                return render(request, 'admins/categories.html')
        else:
            return redirect('customadmin:manage_category')
    else:
        category = Category.objects.all()

    context = {
        'category': category,
    }
    return render(request, 'admins/categories.html', context)

# end manage category

# delete_category


@user_passes_test(lambda u: u in a, login_url='customadmin:admin_login')
def delete_category(request, id):
    category = Category.objects.get(id=id)
    category.delete()
    return redirect('customadmin:manage_category')

# end delete_category

# edit category


@user_passes_test(lambda u: u in a, login_url='customadmin:admin_login')
def edit_category(request, id):
    category = Category.objects.get(id=id)
    form = CategoryEditForm(instance=category)
    try:
        if request.method == 'POST':
            form = CategoryEditForm(request.POST, instance=category)
            if form.is_valid():
                form.save()
                return redirect('customadmin:manage_category')
    except:
        messages.error(request, "Slug already exists.")
        print("slug exists")
        return redirect('customadmin:edit_category')

    context = {
        'form': form
    }
    return render(request, 'admins/edit_category.html', context)

# end edit category

# add_category


@user_passes_test(lambda u: u in a, login_url='customadmin:admin_login')
def add_category(request):
    print(request.method)
    try:
        if request.method == 'POST':
            print('dshfhdgdfhgshdlivsdisd')
            title = request.POST['title']
            slug = request.POST['slug']
            print(title,slug)
            category = Category.objects.create(category_name=title, slug=slug)
            print(category,'=======================')
            category.save()
            return redirect('customadmin:manage_category')
        return render(request, 'admins/add_category.html')
    except:
        messages.error(request, "Slug already exists.")
        return redirect('customadmin:add_category')

# end add category

# manage product


@user_passes_test(lambda u: u in a, login_url='customadmin:admin_login')
def manage_product(request):
    if 'q' in request.GET:
        q = request.GET['q']
        if q:
            product = Product.objects.order_by('-id').filter(Q(category__title__icontains=q) | Q(
                subcategory__name__icontains=q) | Q(gender__icontains=q) | Q(brand__brand_name__icontains=q) | Q(name__icontains=q))
            for single_product in product:
                product1 = []
        for single_product in product:

            product1.append({
                'id': single_product.id,
                'product_name': single_product.product_name,
                'slug': single_product.slug,
                'descrbtion': single_product.descrbtion,
                'price': single_product.price,
                'image': single_product.image,
                'stock': single_product.stock,
                'is_available': single_product.is_available,
                'category': single_product.category,
                'created_date': single_product.created_date,
                'modified_date': single_product.modified_date,
                'offer': (single_product.price-(single_product.category.offer * single_product.price)/100),
            })
        paginator = Paginator(product1, 8)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        if not product.exists():
            messages.error(request, 'No Matching Datas Found')
            return render(request, 'admins/product.html')
        else:
            return redirect('customadmin:manage_product')
    else:
        product = Product.objects.all().order_by('-id')
        for single_product in product:
            product1 = []
        for single_product in product:

            product1.append({
                'id': single_product.id,
                'product_name': single_product.product_name,
                'slug': single_product.slug,
                'descrbtion': single_product.descrbtion,
                'price': single_product.price,
                'image': single_product.image,
                'stock': single_product.stock,
                'is_available': single_product.is_available,
                'category': single_product.category,
                'created_date': single_product.created_date,
                'modified_date': single_product.modified_date,
                'offer': (single_product.price-(single_product.category.offer * single_product.price)/100),
            })
        paginator = Paginator(product1, 8)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)

    context = {
        'product': paged_products,
    }
    return render(request, 'admins/product.html', context)


# end manage product

# add_product

@user_passes_test(lambda u: u in a, login_url='customadmin:admin_login')
def add_product(request):
    form = ItemCreateForm
    try:
        if request.method == 'POST':
            form = ItemCreateForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('customadmin:manage_product')

        return render(request, 'admins/add_product.html', {'form': form})
    except:

customadmin/templates/admins/add_product.html
{% extends 'admins/adminbase.html' %}
{% block content %}
{% load static %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/2.3.4/cropper.min.css" />

<div class="main-panel">        
    <div class="content-wrapper">
      <div class="row d-flex align-items-center justify-content-center">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
            <div class="card-body">
                <h4 class="card-title">Add Product</h4>
                <!-- <p class="card-description">
                Basic form layout
                </p> -->
                <form action="" enctype="multipart/form-data" class="forms-sample" method="POST" id="ItemCreateForm" >
                    {% csrf_token %}
                   
                   
                        {{ form.as_p }}
                        <label for="">image</label><br>
                        <div id="crop">
                            <img id="imgView1" alt="" style="height: 100px; width: 120px" class="clr" />

                            <div class="vald-info" id="info"></div>
                            <h5 class="error_form text-danger" id="image1_error_message"></h5>
                            <div style="display: flex">
                                <div id="image-box1" class="image-container clr" style="height: 300px; width: 20%">
                                </div>
                                <div>
                                    <button type="button" class="betaButton btn btn-success" id="crop-btn1" style="
                                                display: none;
                                                margin: 20px 0px 0px 40px;
                                                position:relative;
                                                top:80%;
                                                left:70%
                                                ">
                                        Crop
                                    </button>
                                </div>
                            </div>
                        </div>

{% comment %} 
                        <input type="file" name="image" class="form-control" onchange="changeImg(event)" id="id_image1"
                            onchange="viewImage1(event)" /><br /> {% endcomment %}
                   
                    
                    <button type="submit" class="btn btn-primary me-2">Submit</button> 
              
                </form>
                {% if messages %}
                {% for message in messages %}
                {{ message }}
                {% endfor %}
                {% endif %}
              
                
            </div>
          
            </div>
        </div>
    
      </div>
    </div>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/0.8.1/cropper.min.js"></script>
<script>
  $("#id_category").change(function () {
    var url = $("#ItemCreateForm").attr("data-subcategory-url");  // get the url of the `load_cities` view
    var categoryId = $(this).val();  // get the selected country ID from the HTML input

    $.ajax({                       // initialize an AJAX request
      url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
      data: {
        'category': categoryId       // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
        $("#id_subcategory").html(data);  // replace the contents of the city input with the data that came from the server
      }
    });

  });

 function changeImg(event) {
        document.getElementById('imgView1').src = URL.createObjectURL(event.target.files[0])
    }
    const imagebox1 = document.getElementById("image-box1");
    const crop_btn1 = document.getElementById("crop-btn1");
    const input1 = document.getElementById("id_image1");
    function viewImage1(event) {
        var fileInput1 = document.getElementById("id_image1");
        var filePath1 = fileInput1.value;
        var allowedExtensions = /(\.jpg)$/i;
        if (!allowedExtensions.exec(filePath1)) {
            fileInput1.value = "";
            swal("There is a problem!", "Please choose image file.");
            return false;
        } else {
            document.getElementById("imgView1").src = URL.createObjectURL(
                event.target.files[0]
            );
        }
    }

    // When user uploads the image this event will get triggered
    input1.addEventListener("change", () => {
        // Getting image file object from the input variable
        const img_data1 = input1.files[0];
        // createObjectURL() static method creates a DOMString containing a URL representing the object given in the parameter.
        // The new object URL represents the specified File object or Blob object.
        const url1 = URL.createObjectURL(img_data1);
        // Creating a image tag inside imagebox which will hold the cropping view image(uploaded file) to it using the url created before.
        imagebox1.innerHTML = `<img src="${url1}" id="image1" style="width:100%;">`;
        // Storing that cropping view image in a variable
        const image1 = document.getElementById("image1");

        // Displaying the image box
        document.getElementById("image-box1").style.display = "block";
        // Displaying the Crop buttton
        document.getElementById("crop-btn1").style.display = "block";
        // Hiding the Post button
        document.getElementById("imgView1").style.display = "block";

        const cropper1 = new Cropper(image1, {
            autoCropArea: 1,
            viewMode: 1,
            scalable: false,
            zoomable: false,
            movable: false,
            minCropBoxWidth: 50,
            minCropBoxHeight: 50,
        });
        // When crop button is clicked this event will get triggered
        crop_btn1.addEventListener("click", () => {
            // This method coverts the selected cropped image on the cropper canvas into a blob object
            cropper1.getCroppedCanvas().toBlob((blob) => {
                // Gets the original image data
                let fileInputElement1 = document.getElementById("id_image1");
                // Make a new cropped image file using that blob object, image_data.name will make the new file name same as original image
                let file1 = new File([blob], img_data1.name, {
                    type: "image/*",
                    lastModified: new Date().getTime(),
 });
                // Create a new container
                let container1 = new DataTransfer();
                // Add the cropped image file to the container
                container1.items.add(file1);
                // Replace the original image file with the new cropped image file
                fileInputElement1.files = container1.files;
                document.getElementById("imgView1").src = URL.createObjectURL(
                    fileInputElement1.files[0]
                );
                // Hide the cropper box
                document.getElementById("image-box1").style.display = "none";
                // Hide the crop button
                document.getElementById("crop-btn1").style.display = "none";


            });
        });
    }); 

</script>
{% endblock %}

customadmin/templates/admins/coupon.html
{% extends 'admins/adminbase.html' %}
{% block content %}
{% load static %}



      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
  
          <div class="row">           
   
           
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                    <div>
                  <h4 class="card-title">All Categories</h4>
                  <a style="text-decoration: none;" href= "{% url 'customadmin:add_discount' %}"> <i class="fa-solid fa-circle-plus "></i><span> &nbsp&nbspAdd New </a>
                  <!-- <p class="card-description">
                    Add class <code>.table-striped</code>
                  </p> -->
                  <div class="table-responsive">
                    <table class="table table-striped mt-5">
                      <thead >
                        <tr>
                          <th>
                           Sl.no.
                          </th>
                          <th>
                           Coupon Code
                          </th> 
                          <th>
                            Discount (*100%)
                           </th>   
                           <th>
                            Start 
                           </th>  
                           <th>
                            End
                           </th>  
                           <th>
                            coupon Name
                           </th>      
                          <th>
                            Actions
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                  
                        {% for x in coupon %}
                        <tr>
                          <td class="py-1">
                            {{ forloop.counter }}
                            
                          </td>
                          <td>
                            {{ x.coupon_code | capfirst}} 
                          </td>
                          <td>
                            {{ x.coupon_offer }} 
                          </td>
                          <td>
                            {{ x.coupon_start }} 
                          </td>
                          <td>
                            {{ x.coupon_end }} 
                          </td>
                          <td>
                            {{ x.coupon_name }} 
                          </td>
                           <td>

                            <a href= "{% url 'customadmin:edit_discount' x.id %}"><i style="color:green" class="fa-solid fa-pen-to-square"></i> </a>
                            <a href= "{% url 'customadmin:delete_discount' x.id %}" onclick="return confirm('Are you sure to delete '+' {{x.title}} ?')"><i style="color:red;margin-inline:50px;"  class="fa-solid fa-trash"></i></a>                                                                                                      
                            
                           </td>
                        </tr>
                       {% endfor %}
                    
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          
          </div>
        </div>
       
{% endblock %}

customadmin/templates/admins/variation.html
{% extends 'admins/adminbase.html' %}
{% block content %}
{% load static %}



      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
  
          <div class="row">           
   
           
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                    <div>
                  <h4 class="card-title">Variations</h4>
                  <a style="text-decoration: none;" href= "{% url 'customadmin:add_variation' %}"><i class="fa-solid fa-circle-plus"></i> Add New </a>
                  <!-- <p class="card-description">
                    Add class <code>.table-striped</code>
                  </p> -->
                  <div class="table-responsive">
                    <table class="table table-striped mt-5">
                      <thead >
                        <tr>
                          <th>
                           Sl.no.
                          </th>
                          <th>
                            Product
                           </th>
                          <th>
                           Variation Category
                          </th> 
                          <th>
                            Variation Value
                           </th>     
                                   
                          <th>
                            Actions
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                  
                        {% for x in variation %}
                        <tr>
                          <td class="py-1">
                            {{ forloop.counter }}
                     
                          </td>
                          <td>
                            {{ x.product| capfirst}} 
                          </td>
                          <td>
                            {{ x.variation_category }} 
                          </td>
                          <td>
                            {{ x.variation_value }} 
                          </td>
                         
                           <td>

                            <a href= "{% url 'customadmin:edit_variation' x.id %}"><i style="color:green" class="fa-solid fa-pen-to-square"></i> </a>
                            <a href= "{% url 'customadmin:delete_variation' x.id %}" onclick="return confirm('Are you sure to delete '+' {{x.title}} ?')"><i style="margin-inline:50px;color:red;" class="fa-solid fa-trash"></i></a>                                                                                                    
                           
                           </td>
                        </tr>
                       {% endfor %}                           
                    
                      </tbody>
                    </table>{% if messages %}
                    {% for message in messages %}
                    {{ message }}
                    {% endfor %}
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          
          </div>
        </div>
       
{% endblock %}