accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('otplogin/', views.otplogin, name='otplogin'),
    path('verify/', views.verify_code, name="verify"),
    path('verifyotp/', views.verifyotp, name="verifyotp"),

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('add_address/', views.add_address, name="add_address"),
    path('address_list/', views.address_list, name="address_list"),
    path('edit_address/<int:address_id>', views.edit_address, name='edit_address'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<str:tracking_no>',
         views.order_detail, name="order_detail"),

]

cart/urls.py
from django.urls import path

from . import views

app_name = "cart"


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart_item, name="remove_cart_item"),
    path('checkout/', views.checkout, name="checkout"),
    path('cancel_order/<id>/', views.cancel_order, name="cancel_order"),

    path('select-address/', views.select_address, name="select_address"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('store/', include('store.urls', namespace="store")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('wishlist/', include('wishlist.urls', namespace="wishlists")),
    path('admins/',include('customadmin.urls', namespace="customadmin")),
    path('', views.home, name='home'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name="orders"


urlpatterns = [
    path('place-order', views.placeorder, name="placeorder"),
    path('my-order', views.my_orders, name="my_orders"),

    # razorpay
    path('proceed-to-pay', views.razorcheck, name="razorcheck"),
]

accounts/models.py
import email
from urllib import request
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.


class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('user must have an email')
        if not username:
            raise ValueError('user must have a username')
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=10, blank=False, null=False)
    
    # required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    # set login field
    USERNAME_FIELD = 'email'
    # set required fields
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True, max_length=100)
    address_line_2 = models.CharField(blank=True, max_length=100)
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    pincode = models.CharField(blank=True, max_length=20)
    is_defualt = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f"{self.address_line_1} {self.address_line_2}"

accounts/views.py
import requests
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import redirect, render
from django.views.decorators.cache import never_cache

from cart.models import Cart, CartItem
from cart.views import _cart_id
from orders.models import Order, OrderItems, ProfileAddress

from .forms import (AddressForm, RegistrationForm, UserForm, UserProfileForm,
                    VerifyForm, VerifyotpForm, otploginForm)
from .models import Account, UserProfile
from .verify import check, send


# Create your views here.
@never_cache
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]

            if Account.objects.filter(phone_number=phone_number).exists():
                messages.error(request, 'Phone number already exists')

            else:
                user = Account.objects.create_user(
                    first_name=first_name, last_name=last_name, email=email, username=username, password=password)
                user.phone_number = phone_number
                user.save()
                request.session['phone_number'] = phone_number
                send(form.cleaned_data.get('phone_number'))
                return redirect('accounts:verify')
    else:
        form = RegistrationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/register.html', context)


def verifyotp(request):
    if request.method == 'POST':
        form = VerifyotpForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data.get('code')
            phone_number = request.session['phone_number']

            if check(phone_number, code):
                print('fdgsdfgdsfgdfgsrf')
                user = Account.objects.get(phone_number=phone_number)

                if user is not None:
                    auth.login(request, user)
                    messages.success(request, 'you are now logged in')
                    return redirect('home')
                else:
                    messages.error(request, 'Invalid credentials')
                    return redirect('accounts:login_page')
    else:
        form = VerifyForm()
    return render(request, 'accounts/verify.html', {'form': form})


def verify_code(request):
    if request.method == 'POST':

        form = VerifyForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data.get('code')
            phone_number = request.session['phone_number']
            print('fdgsdfgdsfgdfgsrf')
            if check(phone_number, code):
                user = Account.objects.get(phone_number=phone_number)
                user.is_active = True
                user.save()
                return redirect('accounts:login_page')
    else:
        form = VerifyForm()
    return render(request, 'accounts/verify.html', {'form': form})


@never_cache
def login_page(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            email = request.POST['email']
            password = request.POST['password']

            user = auth.authenticate(email=email, password=password)

            if user is not None:
                try:
                    cart = Cart.objects.get(cart_id=_cart_id(request))
                    is_cart_item_exists = CartItem.objects.filter(
                        cart=cart).exists()
                    if is_cart_item_exists:
                        cart_item = CartItem.objects.filter(cart=cart)
                        product_variation = []
                        for item in cart_item:
                            variation = item.variations.all()
                            product_variation.append(list(variation))

                        cart_item = CartItem.objects.filter(user=user)
                        ex_var_list = []
                        id = []
                        for item in cart_item:
                            existing_variation = item.variations.all()
                            ex_var_list.append(list(existing_variation))
                            id.append(item.id)

                        for pr in product_variation:
                            if pr in ex_var_list:
                                index = ex_var_list.index(pr)
                                item_id = id[index]
                                item = CartItem.objects.get(id=item_id)
                                item.quantity += 1
                                item.user = user
                                item.save()
                            else:
                                cart_item = CartItem.objects.filter(cart=cart)
                                for item in cart_item:
                                    item.user = user
                                    item.save()
                except:
                    pass
                auth.login(request, user)
                messages.success(request, 'you are now logged in')
                url = request.META.get('HTTP_REFERER')
                try:
                    query = requests.utils.urlparse(url).query
                    params = dict(x.split('=') for x in query.split('&'))
                    if 'next' in params:
                        nextPage = params['next']
                        return redirect(nextPage)

                except:
                    return redirect('home')
            else:
                messages.error(request, 'Invalid credentials')
                return redirect('accounts:login_page')
        return render(request, 'accounts/login.html')


def otplogin(request):
    if request.method == 'POST':
        form = otploginForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data['phone_number']

            if Account.objects.filter(phone_number=phone_number).exists():

                user = Account.objects.get(phone_number=phone_number)
                request.session['phone_number'] = phone_number
                send(form.cleaned_data.get('phone_number'))
                return redirect('accounts:verifyotp')

            else:
                messages.error(request, "Account Doesnot exist!")
        else:
            messages.error(request, "Enter a Valid Phone Number!")
    return render(request, 'accounts/otp_login.html')


@login_required(login_url='accounts:login_page')
@never_cache
def logout(request):
    auth.logout(request)
    messages.success(request, 'you are logged out')
    return redirect('accounts:login_page')


def activate(request, uidb64, token):

    try:
        uid = uidb64
        user = Account._default_manager.get(pk=uid)

    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(
            request, "congratulations your account has been varified")
        return redirect('accounts:login_page')
    else:
        messages.error(request, "Invalid Activation link!")
        return redirect("register")


@login_required(login_url='accounts:login_page')
def dashboard(request):
    orders = Order.objects.order_by(
        "-created_at").filter(user_id=request.user.id)
    orders_count = orders.count
    userprofile = UserProfile.objects.filter(user_id=request.user.id)
    context = {
        'orders_count': orders_count,
        'userprofile': userprofile,
    }
    return render(request, 'accounts/dashboard.html', context)

# add address


def add_address(request):
    if request.method == "POST":
        user = request.user
        address_line_1 = request.POST['address_line_1']
        address_line_2 = request.POST['address_line_2']
        city = request.POST['city']
        state = request.POST['state']
        country = request.POST['country']
        pincode = request.POST['pincode']
        ins = UserProfile(user=user, address_line_1=address_line_1,
                             address_line_2=address_line_2, city=city, state=state, country=country, pincode=pincode)
        ins.save()

    return render(request, 'accounts/add_address.html')
# add address ends here


def address_list(request):
    defualt_add = UserProfile.objects.filter(user=request.user)
    context = {
        'ins': defualt_add
    }
    return render(request, 'accounts/address_list.html', context)


def edit_address(request, address_id):
    profile = UserProfile.objects.get(id=address_id)
    if request.method == "POST":
        profile_form = UserProfileForm(
            request.POST, instance=profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile Updated.')
            return redirect('accounts:address_list')
    else:
        profile_form = AddressForm(instance=profile)
    context = {
        'profile_form': profile_form,
        "userprofile": profile,
    }
    return render(request, 'accounts/edit_address.html', context)


def edit_profile(request):
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile Updated.')
            return redirect('accounts:edit_profile')
    else:
        user_form = UserForm(instance=request.user)
    context = {
        'user_form': user_form,
    }
    return render(request, 'accounts/edit_profile.html', context)

templates/accounts/account_verification_email.html
{% autoescape off %}


Hi {{user.first_name}},
Please Click On The Link Below To Confirm Your Registration.
http://{{domain}}{% url 'activate' uidb64=uid token=token %}

If you think it's not you,Please ignore This mail

{% endautoescape %}

templates/accounts/add_address.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}


{% include "includes/alerts.html" %}
<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            {% include "includes/sidebar.html" %}
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header mb-3">
                        <strong class="d-inline-block ms-3 ">Add Address</strong>

                    </header>

                    <div class="col-md-12">
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Address Line 1</label>
                                <input type="text" name="address_line_1" maxlength="100" class="form-control"
                                    id="id_address_line_1">
                            </div>
                            <div class="form-group">
                                <label>Address Line 2</label>
                                <input type="text" name="address_line_2" maxlength="100" class="form-control"
                                    id="id_address_line_2">
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3 ">
                                    <label>City</label>
                                    <input type="text" name="city" maxlength="20" class="form-control" id="id_city">
                                </div>
                                <div class="form-group col-md-3 ">
                                    <label>State</label>
                                    <input type="text" name="state" maxlength="20" class="form-control" id="id_state">
                                </div>
                                <div class="form-group col-md-3 ">
                                    <label>Country</label>
                                    <input type="text" name="country" maxlength="20" class="form-control"
                                        id="id_country">
                                </div>
                                <div class="form-group col-md-3 ">
                                    <label>Pincode</label>
                                    <input type="text" name="pincode" maxlength="20" class="form-control"
                                        id="id_pincode">
                                </div>
                            </div>
                            <input type="submit" value="Save" class="btn btn-dark  btn-block my-4">

                        </form>

                    </div>
                </article>
            </main>
        </div>
    </div> <!-- card-body .// -->



    <!-- order-group.// -->

    <!-- row.// -->



</section>

{% endblock content %}

templates/accounts/address_list.html
{% extends 'base.html' %}

{% block content %}

{% include "includes/alerts.html" %}

{% load static %}
{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}


<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            {% include "includes/sidebar.html" %}
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3 ">Address List</strong>

                    </header>

                    <div class="col-md-12 overflow-auto">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Address</th>
                                    <th scope="col">City</th>
                                    <th scope="col">State</th>
                                    <th scope="col">country</th>
                                    <th scope="col">pincode</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for address in ins %}
                                <tr>
                                    <th scope="row">{{ address.address_line_1 }},<br>{{address.address_line_2}}</th>
                                    <td>{{address.city}}</td>
                                    <td>{{address.state}}</td>
                                    <td>{{address.country}}</td>
                                    <td>{{address.pincode}}</td>
                                    <th><a href="{% url 'accounts:edit_address' address.id %}" class="btn btn-warning">update</a></th>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
        </div>
    </div> <!-- card-body .// -->



    </article> <!-- order-group.// -->
    </main>
    </div> <!-- row.// -->
    </div>


</section>

{% endblock content %}

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include "includes/alerts.html" %}
{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}



<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            {% include "includes/sidebar.html" %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3 ">Change Password</strong>

            </header>

                 <div class="col-md-12">
                     <form action="{% url 'accounts:change_password' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group mt-3" >
                                <label >Current Password</label>
                                <input type="password" name="current_password" placeholder="Current Password" class="form-control" required>
                            </div>
                        <div class="form-group">
                                <label >New Password</label>
                                <input type="password" name="new_password" placeholder="New Password" class="form-control" required>
                             </div>
                             <div class="form-group">
                                <label >Confirm New Password</label>
                                <input type="password" name="confirm_password" placeholder="Confirm New Password" class="form-control" required>
                             </div>

                        <input type="submit" value="Save" class="btn btn-primary mb-2">
                     </form>

                 </div>
                </div>
            </div> <!-- card-body .// -->



            </article> <!-- order-group.// -->
        </main>
    </div> <!-- row.// -->
    </div>


    </section>

{% endblock content %}

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}



{% include "includes/alerts.html" %}
<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            {% include "includes/sidebar.html" %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Logged In as :</strong>
                <span class="text-success font-weight-bold"> {{ user.first_name }} {{user.last_name}} </span>
            </header>
            <div class="card-body">
                <div class="row">
                 <div class="col-md-6">
                    <div class="card" style="text-align:center;">
                        <div class="card-body">
                            <h5 class="card-title">Total Orders</h5>
                            <h4>{{orders_count}}</h4>
                            <a href="{% url 'orders:my_orders' %}">View Orders</a>
                        </div>
                    </div>
                 </div>
                 <div class="col-md-6">
                    <div class="card " style="text-align:center;">
                        <div class="card-body">
                            <p class=" mt-2 mb-0  text-info">{{ user.email }}</p>
                            <p class="text-info">{{user.phone_number}}</p>
                        </div>
                    </div>
                 </div>
                </div>
            </div> <!-- card-body .// -->
            


            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>

{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}


<section class="vh-100 gradient-custom">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

    {% if request.GET.command == 'verification' %}
    <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
      Thank U for registering with us .we have sent a verification email to your email address {{request.GET.email}}
      <br><br>
      Already Verified? <a href=" {% url 'accounts:login_page' %} ">LOGIN</a>
      </div>
      {% else %}

        <div class="card mx-auto bg-dark" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
            <h2 class="fw-bold mb-2 text-uppercase text-white">Login</h2>
            <p class="text-white-50 mb-5">Please enter your login and password!</p>
          {% include 'includes/alerts.html' %}
          <form action="{% url 'accounts:login_page'%}" method="post">
            {% csrf_token %}
            
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email">
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name="password">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="#" class="float-right">Forgot password?</a> 
                  <a href="{% url 'accounts:otplogin' %}" class="float-left">login with OTP?</a>
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                <button class="btn btn-outline-light btn-lg px-5 b" type="submit">Login</button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    {% endif %}
    
    </section>
{% endblock content %}

templates/accounts/my_orders.html
{% extends 'base.html' %}

{% block content %}

{% include "includes/alerts.html" %}

{% load static %}
{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}


<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            {% include "includes/sidebar.html" %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3 ">Your Order History</strong>
                
            </header>
          
                 <div class="col-md-12">
                    <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">Tracking Number#</th>
                            <th scope="col">Billing</th>
                            
                            <th scope="col">Phone</th>
                            <th scope="col">Order Total</th>
                            <th scope="col">Date</th>
                            <th scope="col">Order Status</th>
                            <th scope="col">Manage Order</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                          <tr>
                           
                            <th scope="row"><a href=" {% url 'accounts:order_detail' order.tracking_no %} ">{{ order.tracking_no }}</a></th>
                            <td>{{order.full_name}}</td>
                            <td>{{order.phone}}</td>
                            <td>{{order.total_price |stringformat:'d'}}</td>
                            <td>{{order.created_at}}</td>
                            <td class="text-success">{{order.status}}</td>
                            <td>{% if order.status == "Cancelled" or order.status == "Delivered" %}  {% else %} <a  href="{% url 'cart:cancel_order' order.id %}" class="btn btn-primary" onclick="return confirm('Are you sure ? You want to cancel the order')" >Cancel</a> {% endif %}</td>
                           
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    
                 </div>
                </div>
            </div> <!-- card-body .// -->
            


            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>

{% endblock content %}

templates/accounts/otp_login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}


<section class="vh-100 gradient-custom">


  <div class="card mx-auto bg-dark" style="max-width: 380px; margin-top:100px;">
    <div class="card-body">
      <h2 class="fw-bold mb-2 text-uppercase text-white">Login with Phone</h2>
      <p class="text-white-50 mb-5">Please enter your Phone Number</p>
      {% include 'includes/alerts.html' %}
      <form action="{% url 'accounts:otplogin'%}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input type="number" class="form-control" placeholder="Mobile Number" name="phone_number">
        </div>

    </div>
    <div class="form-group">
      <button class="btn btn-outline-light btn-lg px-5 mx-5" type="submit">Send OTP</button>
    </div> <!-- form-group// -->
    </form>
  </div> <!-- card-body.// -->
  </div> <!-- card .// -->


</section>
{% endblock content %}