accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('otplogin/', views.otplogin, name='otplogin'),
    path('verify/', views.verify_code, name="verify"),
    path('verifyotp/', views.verifyotp, name="verifyotp"),

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('add_address/', views.add_address, name="add_address"),
    path('address_list/', views.address_list, name="address_list"),
    path('edit_address/<int:address_id>', views.edit_address, name='edit_address'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<str:tracking_no>',
         views.order_detail, name="order_detail"),

]

cart/urls.py
from django.urls import path

from . import views

app_name = "cart"


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart_item, name="remove_cart_item"),
    path('checkout/', views.checkout, name="checkout"),
    path('cancel_order/<id>/', views.cancel_order, name="cancel_order"),

    path('select-address/', views.select_address, name="select_address"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('store/', include('store.urls', namespace="store")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('wishlist/', include('wishlist.urls', namespace="wishlists")),
    path('admins/',include('customadmin.urls', namespace="customadmin")),
    path('', views.home, name='home'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name="orders"


urlpatterns = [
    path('place-order', views.placeorder, name="placeorder"),
    path('my-order', views.my_orders, name="my_orders"),

    # razorpay
    path('proceed-to-pay', views.razorcheck, name="razorcheck"),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='storehome'),
    path('category/<slug:category_slug>/',
         views.store, name='products_by_category'),
    path('color/<slug:color_slug>/', views.store, name='products_by_color'),
    path('size/<slug:size_slug>/', views.store, name='products_by_size'),
    path('<slug:category_slug>/<slug:product_slug>/',
         views.product_detail, name='product_detail'),
    

    path('suggestionapi/', views.suggestionApi, name="suggestionApi"),
    path('search/', views.search, name="search"),
]

wishlist/urls.py
from django.urls import path

from . import views


app_name = 'wishlists'

urlpatterns = [
    path('wishlist', views.wishlist, name='wishlist'),
    path('add_wishlist/<int:product_id>/',
         views.add_wishlist, name="add_wishlist"),
    path('remove_wishlist_item/<int:product_id>/<int:wishlist_item_id>/',
         views.remove_wishlist_item, name="remove_wishlist_item"),

]

templates/includes/alerts.html
{% if messages %}

    {% for message in messages %}
    <div id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
        </div>
    </div>
    {% endfor %}

{% endif %}

templates/includes/footer.html
<!-- Footer Section Begin -->
{% load static %}

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="#"><img src="{% static 'store/img/logo.png'%}" alt=""></a>
                    </div>
                    <p>The customer is at the heart of our unique business model, which includes design.</p>
                    <a href="#"><img src="{% static 'store/img/payment.png'%}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Clothing Store</a></li>
                        <li><a href="#">Trending Shoes</a></li>
                        <li><a href="#">Accessories</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivary</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h6>NewLetter</h6>
                    <div class="footer__newslatter">
                        <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                    
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p>Copyright © Aswanth c p 
                        <script>
                            document.write(new Date().getFullYear());
                        </script>2020
                        All rights reserved | This template is made with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by <a href="" target="_blank"></a>
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
{% block scripts %}

{% endblock %}




{% block js %}{% endblock %}
<script src="{% static 'store/js/bootstrap.min.js'%}"></script>
<script src="{% static 'store/js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'store/js/jquery.nicescroll.min.js'%}"></script>
<script src="{% static 'store/js/jquery.magnific-popup.min.js'%}"></script>
<script src="{% static 'store/js/jquery.countdown.min.js'%}"></script>
<script src="{% static 'store/js/jquery.slicknav.js'%}"></script>
<script src="{% static 'store/js/mixitup.min.js'%}"></script>
<script src="{% static 'store/js/owl.carousel.min.js'%}"></script>
<script src="{% static 'store/js/main.js'%}"></script>
<script src="{% static 'store/js/custom.js'%}"></script>
<script src="{% static 'store/js/checkout.js'%}"></script>



<!-- alertify js  -->
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

<script>
    alertify.set('notifier', 'position', 'top-right');

</script>
</body>

</html>

templates/includes/navbar.html
{% load static %}
<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            <a href="{% url 'accounts:login_page' %}">Sign in</a>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="" alt=""></a>
        <a href="#"><img src="" alt=""></a>
        <a href=""><img src="img/icon/cart.png" alt=""><span>
                0
                <span class="fs15 fw500">Basket</span>
        </a>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
        <p>Free shipping, 30-day return or refund guarantee.</p>
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header border border-5">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p>Free shipping, 30-day return or refund guarantee.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        {% if request.user.is_authenticated %}
                        <div class="header__top__links">
                            <a href="{% url 'accounts:dashboard' %}">DashBoard</a>
                            <a href="{% url 'accounts:logout' %}">logout</a>
                        </div>
                        {% else %}
                        <div class="header__top__links">
                            <ul>
                                <li><a href="{% url 'accounts:login_page' %}">Login</a></li>
                            </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'home' %}"><img src="{% static 'store/img/logo.png'%}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'store:storehome' %}">Shop</a></li>
                        <li><a href="{% url 'cart:cart' %}">Cart</a></li>
                        <li><a href="{% url 'orders:my_orders' %}">Orders</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <!-- <a href="{% url 'store:search' %}" class="search-switch"><img src="{% static 'store/img/icon/search.png'%}" alt=""></a> -->
                    <a href="{% url 'wishlists:wishlist' %}"><img src="{% static 'store/img/icon/heart.png'%}" alt=""></a>
                    <a href="{% url 'cart:cart' %}"><img src="{% static 'store/img/icon/cart.png'%}" alt=""> <span class="badge badge-pill badge-danger notify">{{ cart_count}}</span></a>
                    <!-- <span class="badge badge-pill badge-danger notify">{{ cart_count}}</span> -->
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/includes/sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item {% if '/dashboard/' in request.path %}active{% endif %}" href="{% url 'accounts:dashboard' %}"> Dashboard </a>
        <a class="list-group-item {% if '/orders/' in request.path %}active{% endif %}" href="{% url 'orders:my_orders' %}"> My Orders   </a>
        <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}" href="{% url 'accounts:edit_profile' %}"> Edit Profile </a>
        <a class="list-group-item {% if '/address_list/' in request.path %}active{% endif %}" href="{% url 'accounts:address_list' %}"> Address List </a>
        <a class="list-group-item {% if '/add_address/' in request.path %}active{% endif %}" href="{% url 'accounts:add_address' %}"> Add Address </a>
        <a class="list-group-item {% if '/change_password/' in request.path %}active{% endif %}" href="{% url 'accounts:change_password' %}">Change Password </a>
    </ul>
    <br>
    <a class="btn btn-dark btn-block " href="#"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
    <!--   SIDEBAR .//END   -->
</aside>