cart/urls.py
from django.urls import path

from . import views

app_name = "cart"


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',
         views.remove_cart_item, name="remove_cart_item"),
    path('checkout/', views.checkout, name="checkout"),
    path('cancel_order/<id>/', views.cancel_order, name="cancel_order"),

    path('select-address/', views.select_address, name="select_address"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('store/', include('store.urls', namespace="store")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('wishlist/', include('wishlist.urls', namespace="wishlists")),
    path('admins/',include('customadmin.urls', namespace="customadmin")),
    path('', views.home, name='home'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='storehome'),
    path('category/<slug:category_slug>/',
         views.store, name='products_by_category'),
    path('color/<slug:color_slug>/', views.store, name='products_by_color'),
    path('size/<slug:size_slug>/', views.store, name='products_by_size'),
    path('<slug:category_slug>/<slug:product_slug>/',
         views.product_detail, name='product_detail'),
    

    path('suggestionapi/', views.suggestionApi, name="suggestionApi"),
    path('search/', views.search, name="search"),
]

wishlist/urls.py
from django.urls import path

from . import views


app_name = 'wishlists'

urlpatterns = [
    path('wishlist', views.wishlist, name='wishlist'),
    path('add_wishlist/<int:product_id>/',
         views.add_wishlist, name="add_wishlist"),
    path('remove_wishlist_item/<int:product_id>/<int:wishlist_item_id>/',
         views.remove_wishlist_item, name="remove_wishlist_item"),

]

cart/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from accounts.models import UserProfile
from orders.models import Order
from store.models import Product, Variation

from .models import Cart, CartItem

# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    # if the user is not authenticated or logged in

    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(
                        product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
# cartItem
        is_cart_item_exists = CartItem.objects.filter(
            product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(
                product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:

            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                for item in product_variation:
                    cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart:cart')
# if the user is not authenticated or logged in
    else:

        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(
                        product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
# cart

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))

        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()
# cartItem
        is_cart_item_exists = CartItem.objects.filter(
            product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
        # existing variations
        # current variations
        # item id
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(
                    product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:

            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                for item in product_variation:
                    cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart:cart')

def remove_cart(request, product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(
                product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(
                product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass

    return redirect('cart:cart')


def remove_cart_item(request, product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(
            product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(
            product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart:cart')


def cart(request, total=0, quantity=0, cart_item=None):
    request.session['coupon_offer'] = None
    request.session['coupon_code'] = None
    try:
        tax = 0
        grand_total = 0
        cart_items = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += ((cart_item.product.price-(cart_item.product.category.offer *
                      cart_item.product.price)/100)*cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
        request.session['grand_total'] = grand_total
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'store/cart.html', context)


@login_required(login_url='accounts:login_page')
def checkout(request, total=0, quantity=0, cart_item=None):
    user = UserProfile.objects.filter(user=request.user)
    try:
        tax = 0
        grand_total = 0
        cart_items = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(
                user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += ((cart_item.product.price-(cart_item.product.category.offer *
                      cart_item.product.price)/100)*cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
        'user': user,
    }

    return render(request, 'store/checkout.html', context)


def cancel_order(request, id):
    Order.objects.filter(id=id).update(status="Cancelled")
    return redirect('accounts:my_orders')


def select_address(request, addressid):
    address = UserProfile.objects.get(id = addressid)
    return JsonResponse({'address':address})
    

store/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from category.models import Category
from store.models import Color, Product, ProductGallery, Size


def productlist(products):
    product1 = []
    for single_product in products:
        product1.append({
            'id': single_product.id,
            'product_name': single_product.product_name,
            'slug': single_product.slug,
            'descrbtion': single_product.descrbtion,
            'price': single_product.price,
            'image': single_product.image,
            'stock': single_product.stock,
            'offer': single_product.offer,
            'is_available': single_product.is_available,
            'category': single_product.category,
            'created_date': single_product.created_date,
            'modified_date': single_product.modified_date,
            'offer_product': (single_product.price - (single_product.price * single_product.category.offer) / 100)-(single_product.price - (single_product.price * single_product.category.offer)/100 * single_product.offer)/100,
        })
    return product1


def store(request, category_slug=None, color_slug=None, size_slug=None):

    categories = None
    products = None
    if category_slug != None:
        try:
            categories = get_object_or_404(Category, slug=category_slug)
            products = Product.objects.filter(
                category__in=Category.objects.get(
                    category_name=category_slug).get_descendants(include_self=True)
            )
            # products = Product.objects.filter(
            #     category__in=Category.objects.get(
            #         name=category_slug).get_descendants(include_self=True), is_available=True)
            product1 = productlist(products)
            paginator = Paginator(product1, 8)
            page = request.GET.get('page')
            paged_products = paginator.get_page(page)
            product_count = products.count()
        except Exception as e:
            return redirect('store:storehome')
    elif color_slug != None:
        color = get_object_or_404(Color, slug=color_slug)
        try:
            products = Product.objects.all().filter(
                variations__variation_value=color.name).order_by('id')
            product1 = productlist(products)
            paginator = Paginator(product1, 8)
            page = request.GET.get('page')
            paged_products = paginator.get_page(page)
            product_count = products.count()
        except Exception as e:
            return redirect('store:storehome')
    elif size_slug != None:
        size = get_object_or_404(Size, slug=size_slug)
        try:
            products = Product.objects.all().filter(
                variations__variation_value=size.name).order_by('id')
            product1 = productlist(products)
            paginator = Paginator(product1, 8)
            page = request.GET.get('page')
            paged_products = paginator.get_page(page)
            product_count = products.count()
        except Exception as e:
            return redirect('store:storehome')
    else:

        ordering = request.GET.get('ordering', "")
        price = request.GET.get('price', "")
        products = Product.objects.all().filter(is_available=True).order_by('id')
        if ordering:
            products = products.order_by(ordering)
        if price:
            products = products.filter(price__lt=price)
        product1 = productlist(products)
        paginator = Paginator(product1, 8)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    context = {
        'products': paged_products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context)


def product_detail(request, product_slug, category_slug):
    try:
        single_product = Product.objects.get(
            category__slug=category_slug, slug=product_slug)
        # get the product gallery
        product_gallery = ProductGallery.objects.filter(
            product_id=single_product.id)
        product_offer = (single_product.price - (single_product.price * single_product.category.offer) / 100)-(
            single_product.price - (single_product.price * single_product.category.offer)/100 * single_product.offer)/100,
        # wishlist = WishlistItem.objects.all()
        context = {
            'single_product': single_product,
            'product_offer': product_offer[0],
            'product_gallery': product_gallery,
            # 'wishlist': wishlist,
        }
        if request.GET.get('color'):
            color_ = request.GET.get('color')
            price = single_product.get_price_by_colors(color_)
            single_product.price = price
            context['selected_color']=color_
            context['single_product'] = single_product
            update_price = (price - (price * single_product.category.offer) / 100)-(
            price - (price * single_product.category.offer)/100 * single_product.offer)/100
            print(update_price)
            context['update_price'] = update_price

    except Exception as e:
        raise e

    return render(request, 'store/product_detail.html', context)


# search function

def search(request):
    print(101)
    # print(request.GET["keyword"])
    try:
        if "keyword" in request.GET:
            print(102)
            keyword = request.GET["keyword"]
            if keyword:
                products = Product.objects.order_by("-created_date").filter(
                    Q(descrbtion__icontains=keyword) | Q(product_name__icontains=keyword))
                product_count = products.count()
            product1 = productlist(products)
            context = {
                'products': product1,
                'product_count': product_count,
            }
        return render(request, 'store/store.html', context)
    except Exception as e:
        return redirect('store:storehome')


def suggestionApi(request):
    if 'term' in request.GET:
        qs = Product.objects.filter(
            product_name__icontains=request.GET.get('term'))
        titles = list()
        for product in qs:
            titles.append(product.product_name)
        # titles = [product.title for product in qs]
        return JsonResponse(titles, safe=False)
    return render(request, 'core/home.html')

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}
<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Shop</h4>
                    <div class="breadcrumb__links">
                        <a href="{% url 'home' %}">Home</a>
                        <span>Cart</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="section-content padding-y bg " style="min-height: 50vh;">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->
        {% if not cart_items %}
        <h2 class="text-info text-center">Your cart is empty😒</h2>
        <a href="{% url 'home' %}" class="btn btn-primary " style="margin-left: 40%; margin-top:100px ">Continue
            Shopping</a>
        {% else %}
        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                {% for cart_item in cart_items %}
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm">
                                        </div>
                                        <figcaption class="info">
                                            <a href="{% url 'store:product_detail' cart_item.product.category.slug cart_item.product.slug  %}"
                                                class="title text-dark">{{cart_item.product.product_name}}</a>

                                            <p class="text-muted small">{% if cart_item.variations.all %}
                                                {% for item in cart_item.variations.all %}
                                                {{ item.variation_category| capfirst }} :
                                                {{ item.variation_value |capfirst }} <br>
                                                {% endfor %}
                                                {% endif %}</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td class="align-middle position-relative">
                                    <div class="col-12 w-100">
                                        <div class="input-group input-spinner">
                                            <div class="col-3 input-group-prepend"
                                                style="padding-left: 0px;margin-right: 2px;">
                                                <a href="{% url 'cart:remove_cart' cart_item.product.id cart_item.id %}"
                                                    class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </a>
                                            </div>
                                            <input type="text" class="form-control col-4"
                                                value="{{cart_item.quantity}}">
                                            <div class="input-group-append col-4" style="padding-left: 5px;">
                                                <form action="{% url 'cart:add_cart' cart_item.product.id %}"
                                                    method="POST">
                                                    {% csrf_token %}
                                                    {% for item in cart_item.variations.all %}
                                                    <input type="hidden" name="{{item.variation_category | lower}}"
                                                        value="{{item.variation_value | capfirst}}">

                                                    {% endfor %}
                                                    <button class="btn btn-light" type="submit" id="button-minus"> <i
                                                            class="fa fa-plus"></i> </button>
                                                </form>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div>
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">₹{{cart_item.sub_total |stringformat:'d'}}</var>
                                        <small class="text-muted"> ₹{{cart_item.product.price |stringformat:'d'}} each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a id="cartItem{{cart_item.id}}"
                                        href="{% url 'cart:remove_cart_item' cart_item.product.id  cart_item.id %}"
                                        onclick="submitResult(event,{{cart_item.id}})" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <aside class="col-lg-3">

                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">₹{{total |stringformat:'d'}}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> ₹{{tax |stringformat:'d'}}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Grand Total:</dt>
                            <dd id="grand" class="text-right text-dark b"><strong>
                                ₹{{grand_total|stringformat:'d'}}</strong></dd>
                        </dl>
                        <hr>

                        <a href="{% url 'cart:checkout'%}" class="btn btn-primary btn-block"> Checkout </a>
                        <a href="{% url 'store:storehome' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->

            </aside> <!-- col.// -->


        </div> <!-- row.// -->
        {% endif %}
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div>
    <!-- container .//  -->
    {% comment %} <style>
        .disabled {
            pointer-events: none;
            background: rgba(0, 7, 90, .23);
        }
    </style> {% endcomment %}
</section>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    function submitResult(e,cartId) {

        e.preventDefault();
        // preventDefault()
        Swal.fire({
            title: 'Are you sure?',
            text: "Are you sure You want to delete this item?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'

        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire('Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
                document.getElementById("EditForm").submit();
            }
        })

        var href = document.getElementById("cartItem"+cartId).href

        setTimeout(function () {
            window.location = href

        }, 3000);
    }
</script>


{% endblock content %}

templates/store/wish_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% block css %}
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}

<section class="section-content padding-y bg my-5" style="min-height: 50vh;">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->
        {% if not wishlist_items %}
        <h2 class="text-info text-center">Your wishlist is empty😒</h2>
        <a href="" class="btn btn-primary " style="margin-left: 40%; margin-top:100px ">Continue
            Shopping</a>
        {% else %}
        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Price</th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                {% for wishlist_item in wishlist_items %}
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{{ wishlist_item.product.image.url }}"
                                                class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="{{wishlist_item.product.get_url}}"
                                                class="title text-dark">{{wishlist_item.product.product_name}}</a>

                                            <p class="text-muted small">{% if wishlist_item.variations.all %}
                                                {% for item in wishlist_item.variations.all %}
                                                {{ item.variation_category| capfirst }} : {{ item.variation_value |
                                                capfirst }} <br>
                                                {% endfor %}
                                                {% endif %}</p>
                                        </figcaption>
                                    </figure>
                                </td>

                                <td>
                                    <div class="price-wrap">
                                        <var class="price">₹{{wishlist_item.product.price}}</var>
                                        <small class="text-muted"> ₹{{wishlist_item.product.price}} each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="{% url 'wishlists:remove_wishlist_item' wishlist_item.product.id  wishlist_item.id %}"
                                        id="atag" onclick="submitResult(event)" class="btn btn-danger"> Remove</a>

                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <aside class="col-lg-3">
                <p>{{single_product.id}}</p>
                <a href="{% url 'store:storehome' %}" class="btn btn-light btn-block">Continue Shopping</a>
        </div> <!-- card-body.// -->
    </div> <!-- card.// -->

    </aside> <!-- col.// -->


    </div> <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    function submitResult(e) {
        e.preventDefault();
        // preventDefault()
        Swal.fire({
            title: 'Are you sure?',
            text: "Are you sure You want to delete this item?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'

        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire('Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
                document.getElementById("EditForm").submit();
            }
        })
        var href = document.getElementById("atag").href

        setTimeout(function () {
            window.location = href

        }, 2000);
    }
</script>



{% endblock content %}